version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.19.2"
      TYPE: "FORGE"
      MOTD: "§dBaka Bois§r §lMC§r Server"
      DIFFICULTY: "normal"
      PVP: "FALSE"
      SEED: "-8913466909937400889"
      ENFORCE_WHITELIST: "TRUE"
      WHITELIST_FILE: /extras/whitelist.json
      OVERRIDE_WHITELIST: "TRUE"
      OPS_FILE: /extras/ops.json
      OVERRIDE_OPS: "TRUE"
      OVERRIDE_ICON: "TRUE"
      MEMORY: "2G"
      TZ: "Europe/Berlin"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data
      - /srv/minecraft/whitelist.json:/extras/whitelist.json
      - /srv/minecraft/ops.json:/extras/ops.json
  monitor:
    image: itzg/mc-monitor
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: mc
    depends_on:
      - mc
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8180:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus-tsdb:/prometheus
    depends_on:
      - monitor
  grafana:
    image: grafana/grafana-oss:8.2.0
    user: "1000"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana-lib:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus

